import Head from "next/head";
import HomePage  from "./home/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Group Study App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/group_study.ico" />
      </Head>
      <HomePage />
    </>
  );
}
